<?php

namespace Modules\Subcategory\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Category\Entities\Category;

class SubcategoryDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $subcategories = [
            1 => [
                ['name' => 'General Business'],
                ['name' => 'Others'],
                ['name' => 'Human Resources'],
                ['name' => 'Training'],
                ['name' => 'Advertising'],
                ['name' => 'Printing'],
                ['name' => 'General Office Services'],
                ['name' => 'Marketing'],
                ['name' => 'Retail Services'],
                ['name' => 'Small Business'],
                ['name' => 'Overseas Business'],
                ['name' => 'Consultants'],
                ['name' => 'Pest Contro'],
                ['name' => 'Sales Outsourcing'],
                ['name' => 'Health and Safety'],
                ['name' => 'Secretarial Services'],
                ['name' => 'Market Research'],
                ['name' => 'Fire Safety Consultants'],
                ['name' => 'Public Relations'],
                ['name' => 'Business to Business'],
                ['name' => 'AC Repair Services'],
                ['name' => 'Laundry and Dry Cleaning'],
                ['name' => 'Tailors and Alterations'],
                ['name' => 'Storage Services'],
                ['name' => 'Cold Storage Services'],
                ['name' => 'Garbage Removal'],
                ['name' => 'Recycling'],
                ['name' => 'Baby Sitters'],
                ['name' => 'Cremation Service'],
                ['name' => 'Junk Dealers'],
                ['name' => 'Membership Services'],
                ['name' => 'Pet Grooming'],
                ['name' => 'Kennels'],
                ['name' => 'Animal Shelters'],
                ['name' => 'Adoption Agencies'],
                ['name' => 'Nanny Agency'],
                ['name' => 'Dog Walking'],
                ['name' => 'Timeshares'],
                ['name' => 'Tree Service'],
            ],
            2 => [
                ['name' => 'Communications'],
                ['name' => 'Computer Software Solution'],
                ['name' => 'Web Design'],
                ['name' => 'Internet Service Providers'],
                ['name' => 'Websites'],
                ['name' => 'Computer Services'],
                ['name' => 'IT'],
                ['name' => 'Web Development'],
                ['name' => 'Computer Consumables'],
                ['name' => 'Web Services'],
                ['name' => 'Web Hosting'],
                ['name' => 'Software Applications'],
                ['name' => 'Networking'],
                ['name' => 'Computer Training'],
                ['name' => 'Computer Repair'],
                ['name' => 'Online Content'],
                ['name' => 'Cryptocurrency'],
                ['name' => 'Mail Services'],
                ['name' => 'Scanning Services'],
            ],
            3 => [
                ['name' => 'Arts and Crafts'],
                ['name' => 'Leisure'],
                ['name' => 'Photography'],
                ['name' => 'Sports'],
                ['name' => 'Film, Television and Video'],
                ['name' => 'Fashion'],
                ['name' => 'Pubs and Clubs'],
                ['name' => 'Pets and Animals'],
                ['name' => 'Music'],
                ['name' => 'Parties'],
                ['name' => 'Casinos '],
                ['name' => 'Bookmakers'],
                ['name' => 'Performing Arts'],
                ['name' => 'Hobbies'],
                ['name' => 'Lifestyle Management'],
                ['name' => 'Culture'],
                ['name' => 'Gambling'],
            ],
            4 => [
                ['name' => 'Weddings'],
                ['name' => 'Event Services'],
                ['name' => 'Event Equipment'],
                ['name' => 'Conferences'],
            ],
            5 => [
                ['name' => 'Financial Activity'],
                ['name' => 'Banks, Credit Unions'],
                ['name' => 'Pawnshops'],
                ['name' => 'Legal Services'],
                ['name' => 'Audit and Accounting'],
                ['name' => 'Investment Companies'],
                ['name' => 'Business Management Consulting'],
                ['name' => 'Leasing'],
                ['name' => 'Money Service Business'],
                ['name' => 'Tax Consultants'],
                ['name' => 'Banking Equipment'],
                ['name' => 'Payroll Services'],
                ['name' => 'Dept Counseling'],
            ],
            6 => [
                ['name' => 'Restaurants'],
                ['name' => 'Food Retailers'],
                ['name' => 'Catering'],
                ['name' => 'Food Manufacturing'],
                ['name' => 'Take Aways'],
                ['name' => 'Supermarket'],
                ['name' => 'Cafes'],
                ['name' => 'Wine and Beer'],
                ['name' => 'Catering Equipment'],
                ['name' => 'Cookery'],
                ['name' => 'Food Distributors'],
            ],
            7 => [
                ['name' => 'Doctors and Clinics'],
                ['name' => 'Beauty Professionals'],
                ['name' => 'Pharmacies'],
                ['name' => 'Dentists'],
                ['name' => 'Health Care'],
                ['name' => 'Fitness'],
                ['name' => 'Medical Equipment'],
                ['name' => 'Beauty Products'],
                ['name' => 'Hairdressers'],
                ['name' => 'Cosmetic Surgery'],
                ['name' => 'Massage Therapists'],
                ['name' => 'Opticians'],
                ['name' => 'Complementary Therapy'],
                ['name' => 'Nursing and Care'],
                ['name' => 'Mental Health Care'],
                ['name' => 'Pregnancy and Child Birth'],
                ['name' => 'Personal Care'],
                ['name' => 'Vitamins and Supplements'],
                ['name' => 'Mobility Aids'],
                ['name' => 'Spirituality'],
                ['name' => 'Sewing and Needlework'],
                ['name' => 'Gynecologist '],
            ],
            8 => [
                ['name' => 'Lawyers'],
                ['name' => 'Legal Services'],
                ['name' => 'Wills and Trusts'],
                ['name' => 'Solicitors'],
            ],
            9 => [
                ['name' => 'Industrial Services'],
                ['name' => 'Farming'],
                ['name' => 'Engineering'],
                ['name' => 'Industrial Equipment'],
                ['name' => 'Furniture Manufacturers'],
                ['name' => 'Electrical Service'],
                ['name' => 'Steel Products'],
                ['name' => 'Civil Engineering'],
                ['name' => 'Automotive'],
                ['name' => 'Oil & Gas Companies'],
                ['name' => 'Engineers'],
                ['name' => 'Paper Products'],
                ['name' => 'Industrial Automation'],
                ['name' => 'Pumps Manufacturers'],
                ['name' => 'Energy Suppliers'],
                ['name' => 'Industrial Supplies'],
                ['name' => 'Water Treatment'],
                ['name' => 'Science'],
                ['name' => 'Industrial Premises'],
                ['name' => 'Product Development'],
                ['name' => 'Aerospace'],
                ['name' => 'Disinfecting Services'],
                ['name' => 'Solar Panels'],
                ['name' => 'Carpentry'],
                ['name' => 'Utilities'],
                ['name' => 'Fisheries'],
                ['name' => 'Firearms'],
                ['name' => 'Hunting'],
            ],
            10 => [
                ['name' => 'Electrical Goods'],
                ['name' => 'Hardware Stores'],
                ['name' => 'Home and Garden'],
                ['name' => 'Clothing and Accessories'],
                ['name' => 'Gifts'],
                ['name' => 'Jewellery'],
                ['name' => 'General Merchandise'],
                ['name' => 'Furniture'],
                ['name' => 'Kids'],
                ['name' => 'Mobile Phone Shops'],
                ['name' => 'Textile'],
                ['name' => 'Books'],
                ['name' => 'Shopping Centres'],
                ['name' => 'Music'],
                ['name' => 'Department Stores'],
                ['name' => 'Optical Shop'],
                ['name' => 'Gadgets'],
                ['name' => 'Fishing Equipment'],
                ['name' => 'Cigars and Tobacco'],
                ['name' => 'Camping and Outdoors'],
                ['name' => 'Brand Name'],
                ['name' => 'Outlets'],
                ['name' => 'Duty Free Shop'],
                ['name' => 'Discount Stores'],
                ['name' => 'Secondhand Stores'],
                ['name' => 'Pet Shops'],
            ],
            11 => [
                ['name' => 'Hotels'],
                ['name' => 'Travel Agents'],
                ['name' => 'Apartments'],
                ['name' => 'Tourist Information'],
                ['name' => 'Attractions'],
                ['name' => 'Tour Operators'],
                ['name' => 'Specialist Accommodation'],
                ['name' => 'Visa Agencies'],
                ['name' => 'Places to Visit'],
                ['name' => 'Guest Houses'],
                ['name' => 'Sightseeing'],
                ['name' => 'Hotel & Motel Equipment'],
                ['name' => 'Excursions'],
                ['name' => 'Bed and Breakfast'],
                ['name' => 'Cottages'],
                ['name' => 'Holiday Homes'],
                ['name' => 'Translation Services'],
                ['name' => 'Camping and Caravans'],
                ['name' => 'Self Catering Accommodation'],
                ['name' => 'Recreation'],
            ],
            12 => [
                ['name' => 'Construction'],
                ['name' => 'Construction Equipment'],
                ['name' => 'Chemicals'],
                ['name' => 'Construction Services'],
                ['name' => 'Building Materials'],
                ['name' => 'Architectural Services'],
                ['name' => 'Plumbing Services'],
                ['name' => 'Aluminium Openings'],
                ['name' => 'Decorators'],
                ['name' => 'Locksmiths'],
                ['name' => 'Metals'],
                ['name' => 'Roofing'],
                ['name' => 'Doors'],
                ['name' => 'Plumbers'],
                ['name' => 'Windows'],
                ['name' => 'Concrete'],
                ['name' => 'Construction Training'],
                ['name' => 'Fencing and Fence Materials'],
                ['name' => 'Excavators'],
                ['name' => 'Glass Manufacturing'],
                ['name' => 'Remodeling'],
                ['name' => 'Exterminating and Disinfecting'],
                ['name' => 'Gardeners'],
                ['name' => 'Drywall'],
                ['name' => 'Stone'],
                ['name' => 'Paving'],
                ['name' => 'Handyman'],
                ['name' => 'Lumber'],
                ['name' => 'Forestry'],
                ['name' => 'Sandblasting'],
            ],
            13 => [
                ['name' => 'Logistics'],
                ['name' => 'Transport'],
                ['name' => 'Vehicle Services'],
                ['name' => 'Car Parts and Accessories'],
                ['name' => 'Motorbikes'],
                ['name' => 'Marine Services'],
                ['name' => 'Air Travel'],
                ['name' => 'Transport Agents'],
                ['name' => 'Vehicle Sales'],
                ['name' => 'Car Rental'],
                ['name' => 'Taxis'],
                ['name' => 'Air Transport'],
                ['name' => 'Bicycles'],
                ['name' => 'Driving Schools'],
                ['name' => 'Cargo Services'],
                ['name' => 'Petrol Station'],
                ['name' => 'Haulage'],
                ['name' => 'Tire Dealers'],
                ['name' => 'Auto Repair'],
                ['name' => 'Package Shipping'],
                ['name' => 'Courier Services'],
                ['name' => 'Auto Services'],
                ['name' => 'Vehicle Manufacturers'],
                ['name' => 'Auto Parts- New & Used'],
                ['name' => 'Boats and Boating'],
                ['name' => 'Auto Supplies'],
                ['name' => 'Auto Dealers- New & Used'],
                ['name' => 'Ports and Harbours'],
                ['name' => 'Mechanics'],
                ['name' => 'Bus Line'],
                ['name' => 'Aviation'],
                ['name' => 'Car Wash'],
                ['name' => 'Towing Service'],
                ['name' => 'Auto Insurance'],
                ['name' => 'Rail Transport'],
                ['name' => 'Cruises'],
                ['name' => 'Limousines'],
            ],
            14 => [
                ["name" => "Education"],
                ["name" => "Schools"],
                ["name" => "Organizations"],
                ["name" => "Colleges"],
                ["name" => "Religion"],
                ["name" => "Universities"],
                ["name" => "Foundations"],
                ["name" => "Governmental Entities"],
                ["name" => "Children's Services"],
                ["name" => "Environmental Services"],
                ["name" => "Funeral Directors"],
                ["name" => "Cementries & Memorial Parks"],
                ["name" => "Post Offices"],
                ["name" => "Business Education"],
                ["name" => "Public Transport"],
                ["name" => "Tutoring"],
                ["name" => "Social Work Services"],
                ["name" => "Nonprofit Organizations"],
                ["name" => "Voluntary Organisations"],
                ["name" => "Government Services"],
                ["name" => "Churches"],
                ["name" => "Advice Centres"],
                ["name" => "Charity"],
                ["name" => "Government Offices"],
                ["name" => "After School Programs"],
                ["name" => "Police Departments"],
                ["name" => "Youth Organizations"],
                ["name" => "Kindergartens"],
                ["name" => "Local Authorities"],
                ["name" => "Child Daycare Services"],
                ["name" => "Group Homes"],
                ["name" => "Political"],
                ["name" => "Counseling Services"],
            ],
            15 => [
                ['name' => 'Real Estate Agents'],
                ['name' => 'Interior Design'],
                ['name' => 'Security'],
                ['name' => 'Property Development'],
                ['name' => 'Cleaning'],
                ['name' => 'Fire Safety Equipment'],
                ['name' => 'Property Consultants'],
                ['name' => 'Letting Agents'],
                ['name' => 'Commercial Property'],
                ['name' => 'Removals and Relocation'],
                ['name' => 'Online Property Listings'],
                ['name' => 'Renovation'],
                ['name' => 'Realtors'],
                ['name' => 'Buildings'],
                ['name' => 'Building Maintenance'],
                ['name' => 'Auctions'],
                ['name' => 'Apartment Rental'],
                ['name' => 'Home Improvement'],
                ['name' => 'Overseas Property'],
                ['name' => 'Warehouses'],
                ['name' => 'Property Management'],
                ['name' => 'Vacation Rentals'],
            ],
        ];

        foreach ($subcategories as $key => $value) {

            $category = Category::find($key);

            $category->subcategories()->createMany($value);
        }
    }
}
